@dotnet.exe exec "CSC_DIR\csc.dll"
/noconfig
/nowarn:1701,1702,2008
/fullpaths
/nostdlib+
/platform:x64
/errorreport:prompt
/errorendlocation
/preferreduilang:en-US
/highentropyva+
/lib:"MDK_ROOT\MDK"
/lib:"SE_GAME_DIR\Bin64"
/lib:"DOTNET_48_DIR"
/reference:MDKUtilities.dll,
mscorlib.dll,
netstandard.dll,
Sandbox.Common.dll,
Sandbox.Game.dll,
Sandbox.Graphics.dll,
SpaceEngineers.Game.dll,
SpaceEngineers.ObjectBuilders.dll,
System.Core.dll,
System.dll,
VRage.Audio.dll,
VRage.dll,
VRage.Game.dll,
VRage.Input.dll,
VRage.Library.dll,
VRage.Math.dll,
VRage.Render.dll,
VRage.Render11.dll,
VRage.Scripting.dll
/filealign:512
/out:"%TEMP%\mdkscript.exe"
/subsystemversion:6.00
/utf8output
/langversion:6
/analyzer:Mal.Mdk2.PbAnalyzers.dll
/analyzer:Microsoft.Extensions.FileSystemGlobbing.dll
/additionalfile:"MDK_ROOT\MDK\thumb.png"
"MDK_ROOT\MDK\Bootstrapper.cs"
"INJECT_FILES"
"MDK_ROOT\MDK\.NETFramework,Version=v4.8.AssemblyAttributes.cs"
